server:
  port: 8761
spring:
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
  server:
    wait-time-in-ms-when-sync-empty: 0
